PE/Controllers/PermisosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Aplics.Servicios.Negocio.Solicitudes;
using Aplics.Servicios.Modelos.Solicitudes;
using GRC.Servicios.Utilidades;
using GRC.Servicios.Utilidades.Genericos;
using Aplics.Servicios.Negocio;
using GRC.Servicios.Data.DAO.EF;
using Aplics.Servicios.Entidades.DAO.Nominix;
using Aplics.Servicios.Negocio.Nominix;
using System.Configuration;
using Aplics.Servicios.Modelos.Nominix;
using System.IO;
using System.Web.Services.Description;
using PortalEmpleadosV2.Models;
using Aplics.Servicios.Entidades.DAO;
using System.Threading.Tasks;
using System.Security.Cryptography;

namespace PortalEmpleadosV2.Controllers
{
    
	public class PermisosController : Controller
	{
		private int _UserSign = 0;
		private String urlAPINominix = ConfigurationManager.AppSettings["BaseURLServiciosNominix"];
		private String urlAPIAgilix = ConfigurationManager.AppSettings["BaseURLServiciosAgilix"];
		public PermisosController()
		{
			
		}
		// GET: Permisos
		public ActionResult Index()
		{

            if (Session["TypeRol"] == null && Session["NoEmp"] == null)
            {
				return RedirectToAction("Index", "Home");
            }
			_UserSign = (int)Session["UserSign"];

            
			return View();
		}

		public ActionResult HistoricoDescansos()
		{

            if (Session["TypeRol"] == null && Session["NoEmp"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            ClaseAuditoria<String> pe = new ClaseAuditoria<String>();
			Dashboard resDashboard = new Dashboard();
            try
			{
				pe.UserName = this.Session["UserName"].ToString();
				pe.UserSign = _UserSign;
				pe.Clase = Session["NoEmp"].ToString();
				resDashboard = obtenerHistorialSolicitudes(pe);
			} catch (Exception ex)
			{
				throw ex;
			}

            return View(resDashboard);
        }

		public ActionResult ModalPermiso()
		{

            if (Session["TypeRol"] == null && Session["NoEmp"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

			List<ItemSolicitiud> concep = new List<ItemSolicitiud>();
			try
			{
				ClaseAuditoria<String> peticionDashBord = new ClaseAuditoria<String>();
				String claveEmpleado = this.Session["NoEmp"].ToString();
				peticionDashBord.UserName = this.Session["UserName"].ToString();
				peticionDashBord.UserSign = _UserSign;
				peticionDashBord.Clase = claveEmpleado;
				concep = obtenerConceptosSolicitudes(peticionDashBord);

				foreach (var item in concep)
				{
					Console.WriteLine(item.Descripcion);
				}
			} catch (Exception ex)
			{
				throw ex;
			}
			return View(concep);
		}
		public async Task<ActionResult> AdminSolicitudes()
		{
            if (Session["TypeRol"] == null && Session["NoEmp"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
			Dashboard concep = new Dashboard();
			try
			{
				String id = this.Session["NoEmp"].ToString();
				ClaseAuditoria<String> peticionDashBord = new ClaseAuditoria<String>();
				QueryParameters<Empleados> parametrosE = new QueryParameters<Empleados>();
				parametrosE.where = x => x.UserSign.Equals(id);
				peticionDashBord.Clase = id;
				peticionDashBord.UserName = NominixGenerales.ObtenerEmpleado(id, 1).Name;
				peticionDashBord.UserSign = _UserSign;
				this.Session["UserName"] = peticionDashBord.UserName;
				ViewData["Name"] = peticionDashBord.UserName;

				ClaseAuditoria<String> pe = new ClaseAuditoria<String>();
				String claveEmpleado = this.Session["NoEmp"].ToString();
				pe.UserName = this.Session["UserName"].ToString();
				pe.UserSign = _UserSign;
				pe.Clase = claveEmpleado;
				concep = await obtenerSolicitudes(pe);
		    }
			catch (Exception ex)
			{
				throw ex;
			}
			return View(concep);
		}

		[HttpPost]
		public async Task<ActionResult> aprobarSolicitud(int id,String empleado,String Observaciones)
		{
			String mensaje = String.Empty;
			try
			{
				mensaje = await cambiarStatusSolicitud(id, empleado, this.Session["NoEmp"].ToString(),String.Empty, true,Observaciones, urlAPINominix);
			}
			catch(Exception ex)
			{
				mensaje = "Error en la aprobación: " + ex.Message.ToString();
				throw ex;
			}
			return Content(mensaje);
		}

		[HttpPost]
		public async Task<ActionResult> rechazarSolicitud(int id, String Empleado,String MotivoRechazo, String Observaciones)
		{
			String mensaje = String.Empty;
			try
			{
				mensaje = await cambiarStatusSolicitud(id, Empleado, this.Session["NoEmp"].ToString(), MotivoRechazo, false,Observaciones);
			}
			catch (Exception ex)
			{
				mensaje = "Error en la aprobación: " + ex.Message.ToString();
				throw ex;
			}
			return Content(mensaje);
		}

		private async Task<String> cambiarStatusSolicitud(int id,String empleado, String empleadoAutoriza, String MotivoRechazo,Boolean aprobado,String Observaciones, String urlAPINominix = "")
		{
			String result = String.Empty;
			try
			{
				ClaseAuditoria<SolicitudXAprobar> peticionAprobarSol = new ClaseAuditoria<SolicitudXAprobar>();
				SolicitudXAprobar solicitudXAprobar = new SolicitudXAprobar();
				solicitudXAprobar.Id = id;
				solicitudXAprobar.NumEmpleado = empleado;
				solicitudXAprobar.Aprobar = aprobado;
				solicitudXAprobar.EmpleadoAutoriza = empleadoAutoriza;
				solicitudXAprobar.MotivoRechazo = MotivoRechazo;
				solicitudXAprobar.Observaciones = Observaciones;
				peticionAprobarSol.UserName = this.Session["NoEmp"].ToString();
				peticionAprobarSol.UserSign = _UserSign;
				peticionAprobarSol.Clase = solicitudXAprobar;

				result=await aprobarRechazarSolicitud(peticionAprobarSol, urlAPINominix);
			}
			catch (Exception ex)
			{
				throw ex;
			}
			return result;
		}

		public async Task<ActionResult> ListaPermisos()
		{

            if (Session["TypeRol"] == null && Session["NoEmp"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
			Dashboard concep = new Dashboard();
			try
			{
				String id = this.Session["NoEmp"].ToString();

                this.Session["UserName"] = Session["NombreEmpleado"];
                ViewData["Name"] = Session["NombreEmpleado"];

                ClaseAuditoria<String> pe = new ClaseAuditoria<String>();
				String claveEmpleado = this.Session["NoEmp"].ToString();

                pe.UserName = Session["NoEmp"].ToString();
                pe.UserSign = _UserSign;
				pe.Clase = claveEmpleado;
                concep = await obtenerSolicitudes(pe, urlAPINominix, urlAPIAgilix);
               
            }
            catch (Exception ex)
			{
				throw ex;

			}
			return View(concep);
		}


		/// <summary>
		/// Métdo que registra una solicitud.
		/// </summary>
		/// <param name="peticion">peticion del servicio</param>
		/// <returns>RespuestaData<Solicitud>Solicitud actualizada con el nuevo id</returns>
		public RespuestaData<Solicitud> registrarSolicitud(ClaseAuditoria<Solicitud> peticion,String mediosDias="0")
		{
			RespuestaData<Solicitud> oRespuesta = new RespuestaData<Solicitud>();
			try
			{
				SendMails sm = new Aplics.Servicios.Models.EmailConfig().getConfigMail(true);
				NegocioSolicitudRegistro negocio = new NegocioSolicitudRegistro(peticion.UserSign);
				String empleadoRH = ConfigurationManager.AppSettings["empleadoRH"];
				oRespuesta = negocio.registrarSolicitud(peticion.Clase, sm, empleadoRH,Convert.ToInt32(Session["TypeRolMenuSup"]), mediosDias);
			}
			catch (Exception ex)
			{
				oRespuesta.Respuesta.result = 0;
				oRespuesta.Respuesta.mensaje = ex.Message.ToString();
				throw ex;
			}
            return oRespuesta;
		}

		/// <summary>
		/// Métdo para aprobar o rechazar una solicitud.
		/// </summary>
		/// <param name="peticion">peticion del servicio</param>
		/// <returns>RespuestaSimple con resultado de la operación</returns>
		public async Task<String> aprobarRechazarSolicitud(ClaseAuditoria<SolicitudXAprobar> peticion, String urlAPINominix = "")
		{
			String mensaje = String.Empty;
			RespuestaSimple oRespuesta = new RespuestaSimple();
			try
			{
				NegocioSolicitudAutorizacionRechazo negocio = new NegocioSolicitudAutorizacionRechazo(peticion.UserSign);

				SendMails sm = new Aplics.Servicios.Models.EmailConfig().getConfigMail(true);
				String empleadoRH = ConfigurationManager.AppSettings["empleadoRH"];
				oRespuesta = await negocio.actualizarAutorizacionRechazo(peticion.Clase, sm, empleadoRH,Convert.ToInt32(Session["TypeRolMenuSup"]), urlAPINominix);
			}
			catch (Exception ex)
			{
				oRespuesta.result = 0;
				oRespuesta.mensaje = ex.Message.ToString();
				throw ex;
			}
			if (oRespuesta.result != 1)
			{
				mensaje = oRespuesta.mensaje;
				ViewBag.error = mensaje;

			}
			return mensaje;
		}

		/// <summary>
		/// Métdo que devuelve las solicitudes que puede solicar el empleado con sus saldos.
		/// </summary>
		/// <param name="peticion">peticion del servicio</param>
		/// <returns>RespuestaData<Dashboard>Conceptos que puede perdir el empleado</returns>
		public async Task<Dashboard> obtenerSolicitudes(ClaseAuditoria<String> peticion, String urlAPINominix = "", String urlAPIAgilix = "")
		{
			RespuestaData<Dashboard> oRespuesta = new RespuestaData<Dashboard>();
			try
			{
				NegocioSolicitudDashBoard negocio = new NegocioSolicitudDashBoard();
				oRespuesta = await negocio.obtenerDashboard(peticion.Clase, 0, urlAPINominix, urlAPIAgilix);
			}
			catch (Exception ex)
			{
				oRespuesta.Respuesta.result = 0;
				oRespuesta.Respuesta.mensaje = ex.Message.ToString();
				throw ex;
			}
			return oRespuesta.Datos;
		}

        /// <summary>
		/// Métdo que devuelve las solicitudes que puede solicar el empleado con sus saldos.
		/// </summary>
		/// <param name="peticion">peticion del servicio</param>
		/// <returns>RespuestaData<Dashboard>Conceptos que puede perdir el empleado</returns>

PE/Views/Permisos/AdminSolicitudesPermisos.cshtml
@{
    ViewBag.Title = "AdminSolicitudes";
}


<!-- STYLESHEETS -->

<div class="tittle">
    <div class="title-text">
        Administrador de Vaca
    </div>
    <div class="admin-header">
        <header class="crz-header">Solicitudes</header>
        <header class="crz-header">Comentarios</header>
    </div>
</div>


<!-- CONTENT -->
<div class="not-view" style="flex-direction:column;">
    <div style="display: flex; width: 100%; height: 9vh; justify-content: center; align-items: center;">
        <div style="display: flex; width: 100%; height: 90%; justify-content: space-around; align-items: center; background-color: #ECECEE; border-bottom: 1px solid #00464e;     padding: 5px;">
            <div class="search-bar" style="        display: flex;
        width: 40%;
        border: 1px solid #00464E;
        border-radius: 5px;
        padding: 5px;
        height: 100%;">

                <div class="input-group">

                    <input type="text" style="height: 100%;" class="search-input form-control" placeholder="Buscar por No. de Empleado" aria-label="Search.." />

                    <span class="input-group-btn">
                        <button type="button" class="btn btn-icon">
                            <i class="icon icon-magnify"></i>
                        </button>
                    </span>
                </div>
            </div>

            <div class="search-bar" style=" display: flex; width: 40%; border: 1px solid #00464E; border-radius: 5px; padding: 5px; height: 100%; ">

                <div class="input-group">

                    <input type="text" style="height: 100%;" class="search-input form-control" placeholder="Buscar por Año" aria-label="Search.." />

                    <span class="input-group-btn">
                        <button type="button" class="btn btn-icon">
                            <i class="icon icon-magnify"></i>
                        </button>
                    </span>
                </div>
            </div>

        </div>

    </div>

    <div style="display:flex;">
        <scroll-container class="notifications-list" style="border-right: 1px solid #00464E; border-radius:0">
            <div class="background-list">

                <scroll-page class="request">

                    <div class="data-rqst">
                        <p>Solicitud 04932094 </p>
                        <p>Permiso de Paternidad</p>
                    </div>
                    <div class="date-rqst">
                        <p>Fecha de Solicitud</p>
                        <p>11 Dic 2019</p>
                    </div>

                </scroll-page>
                <hr>
                <scroll-page class="request">

                    <div class="data-rqst">
                        <p>Solicitud 04932094 </p>
                        <p>Permiso de Paternidad</p>
                    </div>
                    <div class="date-rqst">
                        <p>Fecha de Solicitud</p>
                        <p>11 Dic 2019</p>
                    </div>

                </scroll-page>
                <hr>
                <scroll-page class="request">

                    <div class="data-rqst">
                        <p>Solicitud 04932094 </p>
                        <p>Permiso de Paternidad</p>
                    </div>
                    <div class="date-rqst">
                        <p>Fecha de Solicitud</p>
                        <p>11 Dic 2019</p>
                    </div>

                </scroll-page>
                <hr>
                <scroll-page class="request">

                    <div class="data-rqst">
                        <p>Solicitud 04932094 </p>
                        <p>Permiso de Paternidad</p>
                    </div>
                    <div class="date-rqst">
                        <p>Fecha de Solicitud</p>
                        <p>11 Dic 2019</p>
                    </div>

                </scroll-page>
                <hr>
                <scroll-page class="request">

                    <div class="data-rqst">
                        <p>Solicitud 04932094 </p>
                        <p>Permiso de Paternidad</p>
                    </div>
                    <div class="date-rqst">
                        <p>Fecha de Solicitud</p>
                        <p>11 Dic 2019</p>
                    </div>

                </scroll-page>
                <hr>
                <scroll-page class="request">

                    <div class="data-rqst">
                        <p>Solicitud 04932094 </p>
                        <p>Permiso de Paternidad</p>
                    </div>
                    <div class="date-rqst">
                        <p>Fecha de Solicitud</p>
                        <p>11 Dic 2019</p>
                    </div>

                </scroll-page>
                <hr>
                <scroll-page class="request">

                    <div class="data-rqst">
                        <p>Solicitud 04932094 </p>
                        <p>Permiso de Paternidad</p>
                    </div>
                    <div class="date-rqst">
                        <p>Fecha de Solicitud</p>
                        <p>11 Dic 2019</p>
                    </div>

                </scroll-page>
                <hr>
                <scroll-page class="request">

                    <div class="data-rqst">
                        <p>Solicitud 04932094 </p>
                        <p>Permiso de Paternidad</p>
                    </div>
                    <div class="date-rqst">
                        <p>Fecha de Solicitud</p>
                        <p>11 Dic 2019</p>
                    </div>

                </scroll-page>
                <hr>

            </div>
        </scroll-container>

        <scroll-container class="view-notification">

            <scroll-page class="background-list">
                <!--<p class="text-no-view">Da clic en alguna notificación para vizualizarla aquí</p>-->
                @Html.Partial("_solicitudPermiso")

            </scroll-page>

        </scroll-container>
    </div>


</div>

<!-- CONTENT -->

PE/Views/Permisos/CalendarioEmp.cshtml
    
    
    
    
    
    
    <link rel="stylesheet" href="~/calendarAplics/css/font-awesome.min.css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="~/calendarAplics/css/styles.css">
    <link rel='stylesheet' type='text/css' href='~/calendarAplics/css/fullcalendar.css' />
    <script type='text/javascript' src='~/calendarAplics/js/moment.min.js'></script>
    <script type='text/javascript' src='~/calendarAplics/js/fullcalendar.min.js'></script>
    <script type='text/javascript' src='~/calendarAplics/js/locale/es.js'></script>
    <script>

        function getData() {
            var data;
            $.ajax({
                type: "POST",
                traditional: true,
                async: false,
                cache: false,
                url: '@Url.Action("CalendarioListaEventos","Permisos")',
                dataType: 'json',
                success: function (response) {
                    data = response;
                }
            });
            //console.log('hola mundo1');
            //console.log(data);
            return data;
        }

        function addZero(i) {
            if (i < 10) {
                i = '0' + i;
            }
            return i;
        }

        var hoy = new Date();
        var dd = hoy.getDate();
        if (dd < 10) {
            dd = '0' + dd;
        }

        if (mm < 10) {
            mm = '0' + mm;
        }

        var mm = hoy.getMonth() + 1;
        var yyyy = hoy.getFullYear();

        dd = addZero(dd);
        mm = addZero(mm);

        $(document).ready(function () {
            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },
                defaultDate: yyyy + '-' + mm + '-' + dd,
                buttonIcons: true, // show the prev/next text
                weekNumbers: false,
                editable: true,
                eventLimit: true, // allow "more" link when too many events
                events: getData(),
                dayClick: function (date, jsEvent, view) {
                    alert('Has hecho click en: ' + date.format());
                },
                eventClick: function (calEvent, jsEvent, view) {
                    $('#event-title').text(calEvent.title);
                    $('#event-description').html(calEvent.description);
                    $('#modal-event').modal();
                },
            });
        });

    </script>


        <div class="row">
            <div id="content" class="col-lg-12">
                <div id="calendar"></div>
                <div class="modal fade" id="modal-event" tabindex="-1" role="dialog" aria-labelledby="modal-eventLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="event-title"></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div id="event-description"></div>
                            </div>
                            @*<div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-primary">Save changes</button>
                            </div>*@
                        </div>
                    </div>
                </div>
            </div>
        </div>

PE/Views/Permisos/HistoricoDescansos.cshtml
@using Aplics.Servicios.Modelos.Solicitudes
@model Dashboard
@*@model DashboardxEjercicio*@

@{
    ViewBag.Title = "HistoricoDescansos";
    List<Aplics.Servicios.Modelos.Solicitudes.ItemSolicitiud> ListaConceptos = new List<Aplics.Servicios.Modelos.Solicitudes.ItemSolicitiud>();
}
<!-- STYLESHEETS -->
<link href="~/Content/permisos/historicodescansos.css?version=1.3" rel="stylesheet" />

<script src="~/Scripts/Permisos/SolicitudesPermisos.js" asp-append-version="true"></script>

<script>
    $(document).ready(function () {
        $("#toggle-btn").click(function () {
            $("#toggle-example").collapse('toggle'); // toggle collapse
        });
    });
</script>

<!-- CONTENT -->
<div class="tittle">
    Histórico de Descansos
</div>

<div class="not-views">
    <div class="header-historico">
        <div class="user-data">
            <p id="userName">@this.Session["NombreEmpleado"].ToString()</p>
            <p id="userNumber">No. de Empleado: @this.Session["NoEmp"].ToString()</p>
            <p id="yearMember">Miembro desde: @this.Session["AnioIngreso"].ToString()</p>
        </div>

        <div class="box-button">
            <button id="btnNuevaSolicitud" type="button" form="form1" value="Submit" class="btn float-right" style=" text-transform: capitalize;background-color:#3949ab; border-color: #3949ab; height: 4vw; width: 14vw; border-radius: 10px; color:#FFFFFF; font-family: 'Raleway'; font-weight: 600; font-size:1.5vw; " data-toggle="modal" data-target="#modalNewRequest"> Nueva Solicitud </button>

        </div>
    </div>
    <div class="year-view">
        @foreach (DashboardSolicitud da in Model.Solicitudes)
        {
            @*@foreach (DashboardxEjercicio.DescansosAnual da in Model.TableroDescanso)*@


            using (Html.BeginForm("ListaDescansosAnual", "Permisos", FormMethod.Post, new { @id = "form_" + da.Id, @class = "mt-8" }))
            {
                @*<div class="card" style="border-radius: 10px;" onclick='$("#submit-input").click();'>*@
                @*<div class="card" style="border-radius: 10px; cursor:pointer;" onclick='$("#submit-input@(da.Id)").click();'>*@
                <div class="card" style="border-radius: 10px; cursor:pointer;">
                    <div class="card-tittle" style="        background-color: #5599EF;">
                        @da.Id
                    </div>
                    <div class="card-content">
                        <p class="balances">Te corresponden: @System.Math.Round(da.DiasCorrespondientes, 1) días</p>
                        <p class="balances">Tienes disponibles: @System.Math.Round(da.DiasDisponibles, 1) días</p>
                        <p class="balances">Has disfrutado: @System.Math.Round(da.DiasDisfrutados, 1) días</p>
                        <p class="balances">Por aprobar: @System.Math.Round(da.DiasPorAprobar, 1) días</p>
                    </div>
                    <div class="box-buttons-hist-perm">
                        <input type="submit" onclick="form_@(da.Id).flagVacaciones.value = '1';" value="Vacaciones" name="btnVacaciones" id="submit-vacaciones@(da.Id)" class="btn-vacaciones" />
                        <input type="submit" onclick="form_@(da.Id).flagPermisos.value = '1';" value="Permisos" name="btnPermisos" id="submit-permisos@(da.Id)" class="btn-permiso" />
                    </div>
                </div>
                <input id="submit-input@(da.Id)" type="submit" form="form_@(da.Id)" style="display:none" />
                <input name="anio" type="hidden" value="@da.Id" id="anio" />
                <input name="test" type="hidden" value="hola" id="test" />
                <input type="hidden" value="0" id="flagVacaciones" Name="flagVacaciones" />
                <input type="hidden" value="0" id="flagPermisos" Name="flagPermisos" />

            }
        }
    </div>


    <div style="width:100%;
        justify-content: center;
            display: flex;
                flex-direction: column;
                align-items: center;">
        <!-- Toogle Buttons -->

        <div class="box-button-help" style="text-align:center; width:15%;" id="toggle-btn"
             data-toggle="collapse" data-target="#toggle-example">
            <button class="expand-button" type="button" style="width: 100%;">
                ¿Tienes Dudas?
            </button>
            <i class="icon s-12 icon-arrow-down-drop float-center" style="color: #00464E;"></i>
        </div>


        @*<div id="toggle-example" class="collapse in">
                <p>
                    If you don't like something, <b>change it</b>.
                    If you can't change it, change your <b>attitude</b>.
                </p>
            </div>*@

        <div class="collapse in" id="toggle-example" role="tabpanel" style="width: 100%; padding:1%; justify-content: center; align-items: center; color: #00464E; font-size: 2rem; text-align: justify;">
            <div class="step-1">
                <p>En este apartado puedes encontrar los días que te corresponden por año laborado en la empresa.</p>
                <img src="../assets/images/user-help/card-2019.png" alt="imagen tarjeta por año">
            </div>
            <div class="step-2">
                <p>
                    Al hacer click sobre alguna tarjeta, se desplegará el historial de descansos que solicitaste ese año.
                    Puedes filtrar para ver solo los aprobados, los rechazados o los pendientes.
                </p>
                <img src="../assets/images/user-help/2019-lista.png" alt="imagen histórico de año">
            </div>
            <div class="step-3">
                <div class="box-text-step3">
                    <p>Para acceder al formulario y solicitar vacaciones y otros permisos pulsa el botón: </p>
                    <img class="img-button-nr" src="../assets/images/user-help/boton-nueva-solicitud.png" alt="imagen botón nueva solicitud de ejemplo">
                </div>
                <img class="img-new-rqst" src="../assets/images/user-help/form-nueva-sol.png" alt="imagen cómo solicitar un permiso">
            </div>
            <div class="step-4">
                <p>Serás notificado cuando tu superior y/o RH aprueben tu solicitud.</p>
                <img src="../assets/images/user-help/notificacion.png" alt="imagen ejemplo de notificación">
            </div>

            <div class="footer">
                <p>¡Así de fácil!</p>
                <p>¡Solicita tus vacaciones de forma ágil!</p>
            </div>
        </div>

    </div>

    @*<div class="user-help">

            <div class="box-button-help" data-toggle="collapse" data-parent="#userHelpAccordion" href="#userHelpAccordion" aria-expanded="false" aria-controls="userHelpAccordion">
                <button class="expand-button">¿Tienes Dudas?</button>
                <i class="icon s-9 icon-arrow-down-drop float-center" style="color: #00464E;"></i>
            </div>

            <div class="instructions collapse" id="userHelpAccordion" role="tabpanel">
                <div class="step-1">
                    <p>En este apartado puedes encontrar los días que te corresponden por año laborado en la empresa.</p>
                    <img src="../assets/images/user-help/card-2019.png" alt="imagen tarjeta por año">
                </div>
                <div class="step-2">
                    <p>
                        Al hacer click sobre alguna tarjeta, se desplegará el historial de descansos que solicitaste ese año.
                        Puedes filtrar para ver solo los aprobados, los rechazados o los pendientes.
                    </p>
                    <img src="../assets/images/user-help/2019-lista.png" alt="imagen histórico de año">
                </div>
                <div class="step-3">
                    <div class="box-text-step3">
                        <p>Para acceder al formulario y solicitar vacaciones y otros permisos pulsa el botón: </p>
                        <img class="img-button-nr" src="../assets/images/user-help/boton-nueva-solicitud.png" alt="imagen botón nueva solicitud de ejemplo">
                    </div>
                    <img class="img-new-rqst" src="../assets/images/user-help/form-nueva-sol.png" alt="imagen cómo solicitar un permiso">
                </div>
                <div class="step-4">
                    <p>Serás notificado cuando tu superior y/o RH aprueben tu solicitud.</p>
                    <img src="../assets/images/user-help/notificacion.png" alt="imagen ejemplo de notificación">
                </div>

                <div class="footer">
                    <p>¡Así de fácil!</p>
                    <p>¡Solicita tus vacaciones de forma ágil!</p>
                </div>
            </div>


        </div>*@

</div>


@Html.Partial("_modalPermiso", ListaConceptos)

<script type="text/javascript">
    function test() {
        alert('asdfasdf');
    }
</script>

<script type="text/javascript">

    $(document).ready(function () {
        $("#btnNuevaSolicitud").click(function () {
            //alert("Handler for .click() called.");
            //fillCombo("tipo", "2020-03-29");

            console.log("hola mundo 1");

            //var arrayList = [
            //    { "Id": 100, "Name": "Abc" },
            //    { "Id": 200, "Name": "XYZ" }
            //];

            console.log("@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()");
            console.log("@Url.Action("LlenaComboTipo","Permisos",null,Request.Url.Scheme)");

            $("#tipoLoading").fadeTo(100, 1);
            $("#solicitar").prop("disabled", true);
            $("#fechaIni").prop("disabled", true);
            $("#fechaFin").prop("disabled", true);
            $("#file").prop("disabled", true);
            $("#iconfileSub").prop("disabled", true);

            //$.getJSON("/Permisos/LlenaComboTipo", function (data) {
            $.getJSON("@Url.Action("LlenaComboTipo","Permisos",null,Request.Url.Scheme)", function (data) {
                //console.log("hola mundo 2");
                for (var i = 0; i <= data.length - 1; i++) {
                    if (data[i].Politica == true) {
                        $('#tipo').append('<option value="' + data[i].Id + '" data-tope="' + data[i].Tope + '">' + data[i].Descripcion + '</option>');
                    }
                }

                console.log("hola mundo 2");

                $("#tipoLoading").fadeTo(100, 0);
                $("#solicitar").prop("disabled", false);
                $("#fechaIni").prop("disabled", false);
                $("#fechaFin").prop("disabled", false);
                $("#file").prop("disabled", false);
                $("#iconfileSub").prop("disabled", false);

            });

        });
    });

</script>