PE/Models/Horarios/CalendarioSemanalfn.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Aplics.Servicios.Modelos.Horarios
{
    public static class CalendarioSemanalfn
    {
        public static void horasDia(byte inicio, byte fin, ref List<Tiempo> lista)
        {
            for (byte x = inicio; x <= fin; x++)
            {
                lista.Add(new Tiempo(x));
            }
        }
    }
}

PE/Models/Horarios/Empleado.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
namespace Aplics.Servicios.Modelos.Horarios
{
	public class Empleado
	{
		private int _Id = 0;
		[Display(Description ="Clave")]
		public int Id { get => _Id; set => _Id=value; }
		private String _nombre = String.Empty;
		[Display(Description ="Nombre")]
		public String nombre { get => _nombre; set => _nombre = value; }

        private String _puesto = String.Empty;
        [Display(Description = "Puesto")]
        public String puesto { get => _puesto; set => _puesto = value; }

        private String _codigo = String.Empty;
        [Display(Description = "Código")]
        public String codigo { get => _codigo; set => _codigo = value; }

        public Empleado()
		{

		}

		public Empleado(int pId, String pnombre)
		{
			_Id = pId;
			_nombre = pnombre;
		}
	}
}

PE/Models/Horarios/EmpleadoDatosGenerales.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace Aplics.Servicios.Modelos.Horarios
{
	public class EmpleadoDatosGenerales
	{
		private int _DocEntry = 0;
		[Display(Description = "Clave")]
		public int DocEntry { get => _DocEntry; set => _DocEntry = value; }
		private String _NoEmpleado = String.Empty;
		[Display(Description = "No. Empleado")]
		public String NumEmpleado { get => _NoEmpleado; set => _NoEmpleado = value; }
		private String _nombre = String.Empty;
		[Display(Description = "Nombre")]
		public String Nombre { get => _nombre; set => _nombre = value; }
		[Display(Description = "Superior")]
		public String NombreSuperior { get; set; }
	}
}

PE/Models/Horarios/EmpleadoEstudiante.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Aplics.Servicios.Modelos.Horarios
{
	public class EmpleadoEstudiante
	{
		private int _Id = 0;
		[Display(Description = "Clave")]
		public int Id { get => _Id; set => _Id = value; }
		private String _nombre = String.Empty;
		[Display(Description = "Nombre")]
		public String nombre { get => _nombre; set => _nombre = value; }

		[Required]
		[MaxLength(8)]
		[Display(Description = "Cod. Emp.")]
		public String U_EMP { get; set; }
		private short _U_ANIO = (short)System.DateTime.Today.Year;
		[Required]
		[Display(Description = "Año")]
		public short U_ANIO { get => _U_ANIO; set => _U_ANIO = value; }
		[Required]
		[Display(Description = "Período")]
		public short U_PER { get; set; }
		[Required]
		[Display(Description = "Duración")]
		public short U_DUR { get; set; }
		[Required]
		[Display(Description = "Fecha Inicial")]
		public DateTime U_FINI { get; set; }
		[Required]
		[Display(Description = "Fecha Final")]
		public DateTime U_FFIN { get; set; }
		[Display(Description = "Aprobado")]
		[Required]
		public Boolean U_Aprobado { get; set; }
		[Display(Description = "Horario académico")]
		[Required]
		public Boolean U_HorarioESC { get; set; }

		private DateTime _FechaSolicitud = System.DateTime.Now;
		[Required]
		[Display(Description = "Fecha de Solicitud")]
		public DateTime FechaSolicitud { get => _FechaSolicitud; set => _FechaSolicitud = value; }

		private String _motivoRechazo = String.Empty;
		public String motivoRechazo { get => _motivoRechazo; set => _motivoRechazo = value; }
		private short _U_NUMREC = 0;
		[Display(Description = "No. Rechazos")]
		public short U_NUMREC { get => _U_NUMREC; set => _U_NUMREC = value; }
		private String _U_CVEUNI = String.Empty;
		[Display(Description = "Cve. Universidad")]
		public String U_CVEUNI { get => _U_CVEUNI; set => _U_CVEUNI = value; }
		[Display(Description = "Status")]
		public String Status { get; set; }

		private String _Duracion = String.Empty;
		[Display(Description = "Duración")]
		public String Duracion { get => _Duracion; set => _Duracion = value; }
		private String _Universidad = String.Empty;
		[Display(Description = "Universidad")]
		public String Universidad { get => _Universidad; set => _Universidad = value; }
		private String _Observaciones = String.Empty;
		[Display(Description = "Observaciones")]
		public String Observaciones { get => _Observaciones; set => _Observaciones = value; }
		public CalendarioSemanal ocalendario { get; set; }
		public List<TipoConstancia> constancias { get; set; } = new List<TipoConstancia>();

        private String _puesto = String.Empty;
        [Display(Description = "Puesto")]
        public String Puesto { get => _puesto; set => _puesto = value; }

        public List<VMHorarioLista> HorariosSolicitud { get; set; } = new List<VMHorarioLista>();

    }
}

PE/Models/Horarios/EmpleadoHorario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace Aplics.Servicios.Modelos.Horarios
{
	public class EmpleadoHorario : EmpleadoDatosGenerales
	{
		public DateTime Inicio { get; set; }
		public DateTime Fin { get; set; }
		public Boolean Aprobado { get; set; }
		[Display(Description = "Horario académico")]
		public Boolean U_HorarioESC { get; set; }
		private String _motivoRechazo = String.Empty;
		[Display(Description = "Motivo de Rechazo")]
		public String U_MOTIVOREC { get => _motivoRechazo; set => _motivoRechazo = value; }
		private short _U_NUMREC = 0;
		[Display(Description = "No. Rechazos")]
		public short U_NUMREC { get => _U_NUMREC; set => _U_NUMREC = value; }
	}
}

PE/Controllers/DocumentosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Aplics.Servicios.Modelos.Nominix;
using GRC.Servicios.Utilidades.Genericos;
using GRC.Servicios.Data.DAO.EF;
using Aplics.Servicios.Entidades.DAO.Nominix;
using Aplics.Servicios.Modelos.Solicitudes;
using Aplics.Servicios.Negocio.Nominix;
using PortalEmpleadosV2.Models;

namespace PortalEmpleadosV2.Controllers
{
    public class DocumentosController : Controller
    {
        // GET: Documentos
        public ActionResult Index()
        {
            if (Session["TypeRol"] == null && Session["NoEmp"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            List<Documento> Documentos = new List<Documento>();
			try
			{
				Documentos = NominixGenerales.permisosDocumentos(this.Url.Action("Index", "Documentos"), Server.MapPath("~/EmpFiles/"), Session["TypeRol"].ToString(), Session["NoEmp"].ToString());
			}
			catch (Exception ex)
			{
				throw ex;
			}
			ViewBag.Titulo = "Mis Documentos";

			return View(Documentos);
        }

		[HttpPost]
		public ActionResult ContenidoCarpeta(String Ruta)
		{

            if (Session["TypeRol"] == null && Session["NoEmp"] == null)
            {
                return RedirectToAction("Index", "Home");
            }


            List<Documento> Documentos = new List<Documento>();
			try
			{
				Documentos = NominixGenerales.permisosDocumentos(this.Url.Action("Index", "Documentos"), Server.MapPath("~/EmpFiles/"), Session["TypeRol"].ToString(), Session["NoEmp"].ToString(), Ruta);
			}
			catch (Exception ex)
			{
				throw ex;
			}
			return View("Index",Documentos);
		}
	}
}

PE/Controllers/HorariosController.cs
using Aplics.Servicios.Modelos.Generales;
using Aplics.Servicios.Modelos.Horarios;
using Aplics.Servicios.Negocio;
using Aplics.Servicios.Negocio.Horarios;
using GRC.Servicios.Utilidades;
using GRC.Servicios.Utilidades.Genericos;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Aplics.Servicios.Modelos.Nominix;
using GRC.Servicios.Data.DAO.EF;
using Aplics.Servicios.Entidades.Horarios;
using Aplics.Servicios.Negocio.Nominix;
using Aplics.Servicios.Entidades.DAO.Nominix;

namespace Aplics.Servicios.Horarios.Controllers
{
     public class HorariosController : Controller
	{
		int _UserSign = 0;
		public HorariosController()
        {
		}

		// GET: Permisos
		public ActionResult Index()
		{
            if (Session["TypeRol"] == null && Session["NoEmp"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
			_UserSign = (int)Session["UserSign"];
			return View();
		}

		public ActionResult HorariosStatus(string flagNotificaSolicitudPendiente = null)
		{
            if (Session["TypeRol"] == null && Session["NoEmp"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
			EmpleadoEstudiante empleado = new EmpleadoEstudiante();
			try
			{
				ViewBag.NotificacionSolicitudPendiente = flagNotificaSolicitudPendiente;
				ViewBag.Perfil = "EMP";
				List<EmpleadoEstudiante> ListaSolicitudesEmpleado = SolicitudesEstudiantesXStatus("T");
				ListaSolicitudesEmpleado = ListaSolicitudesEmpleado.Where(x => x.U_EMP.Equals(this.Session["NoEmp"].ToString())).ToList();
				ViewBag.ListaSolicitudes = ListaSolicitudes(ListaSolicitudesEmpleado);
				ViewBag.HorariosEmpleado = new List<VMHorarioLista>();

				ViewBag.Estatus = "P";
				if (ListaSolicitudesEmpleado.Count > 0)
				{
					ListaSolicitudesEmpleado = ListaSolicitudesEmpleado.OrderByDescending(x => x.Id).ToList();
					int id = ListaSolicitudesEmpleado[0].Id;
					empleado = BuscaEmpleadoAsignacionXId(id);
					obtieneConstancia(empleado.U_EMP, id);
					ViewBag.HorariosEmpleado = horariosEmp(id, 0);

				}
		    }
			catch (Exception ex)
			{
				throw ex;
			}

			//return View("HorariosStatus", empleado);
			return View("HorariosStatus2", empleado);
		}

		private List<ResumenSolicitud> ListaSolicitudes(List<EmpleadoEstudiante> ListaSolicitudesEmpleado)
		{
			List<ResumenSolicitud> Solicitudes = new List<ResumenSolicitud>();
			try
			{
				if (ListaSolicitudesEmpleado != null)
				{
					foreach (EmpleadoEstudiante solempleado in ListaSolicitudesEmpleado)
					{
						Solicitudes.Add(new ResumenSolicitud() { Id = solempleado.Id, Fecha = solempleado.FechaSolicitud, TipoSolicitud = "Horario", ClaveTipoSolicitud = "H" });
					}
				}
			}
			catch (Exception ex)
			{
				throw ex;
			}

			return Solicitudes.OrderByDescending(x => x.Id).ToList();
		}

		public ActionResult BusqSolicitudesHorarios()
		{
			if (Session["TypeRol"] == null && Session["NoEmp"] == null)
			{
				return RedirectToAction("Index", "Home");
			}
			EmpleadoEstudiante empleado = new EmpleadoEstudiante();
			try
			{
				ViewBag.Titulo = "Buscar Solicitudes de Horarios";
				ViewBag.Perfil = "Admin";
				List<EmpleadoEstudiante> ListaSolicitudesEmpleado = SolicitudesEstudiantesXStatus("AR").OrderByDescending(y => y.Id).ToList();
				List<VMHorarioLista> HorariosEmpleado = new List<VMHorarioLista>();
				if (ListaSolicitudesEmpleado.Count() > 0)
				{
					int idSol = ListaSolicitudesEmpleado[0].Id;
					empleado = BuscaEmpleadoAsignacionXId(idSol);
					HorariosEmpleado = horariosEmp(idSol, 0);
					obtieneConstancia(empleado.U_EMP, idSol);
				}
				ViewBag.ListaSolicitudes = ListaSolicitudes(ListaSolicitudesEmpleado);
				ViewBag.HorariosEmpleado = HorariosEmpleado;
				List<EmpleadoEstudiante> HistorialEmpleadoSeleccionado = SolicitudesHistoricoEstudiantesXEmp(empleado.U_EMP);
				ViewBag.HistorialSeleccionado = HistorialEmpleadoSeleccionado;
				ViewBag.EmpleadoSeleccionado = empleado.U_EMP;
			}
			catch (Exception ex)
			{
				throw ex;
			}
			return View("SolicitudesHorarios", empleado);
		}

		public ActionResult BusqSolicitudesHorariosEstxId(int Id)
		{
			if (Session["TypeRol"] == null && Session["NoEmp"] == null)
			{
				return RedirectToAction("Index", "Home");
			}
			EmpleadoEstudiante empleado = new EmpleadoEstudiante();
			try
			{
				empleado = busqSolHorariosEst(Id);

			}
			catch (Exception ex)
			{
				throw ex;
			}
			return View("SolicitudesHorarios", empleado);
		}

		public ActionResult BusqSolicitudesHorariosEst()
		{
			if (Session["TypeRol"] == null && Session["NoEmp"] == null)
			{
				return RedirectToAction("Index", "Home");
			}
			EmpleadoEstudiante empleado = new EmpleadoEstudiante();
			try
			{
				empleado = busqSolHorariosEst();
			}
			catch (Exception ex)
			{
				throw ex;
			}
			return View("SolicitudesHorarios", empleado);
		}

		private EmpleadoEstudiante busqSolHorariosEst(int id = 0)
		{
			EmpleadoEstudiante empleado = new EmpleadoEstudiante();

			try
			{
				ViewBag.Titulo = "Notificaciones de Horarios";
				ViewBag.Perfil = "Estudiante";
				List<EmpleadoEstudiante> ListaSolicitudesEmpleado = SolicitudesEstudiantesXStatus("AR");
				ListaSolicitudesEmpleado = ListaSolicitudesEmpleado.Where(y => y.U_EMP == this.Session["NoEmp"].ToString()).OrderByDescending(z => z.Id).ToList();
				List<VMHorarioLista> horariosEmpleado = new List<VMHorarioLista>();
				if (ListaSolicitudesEmpleado.Count() > 0)
				{
					int index = 0;
					if (id > 0)
					{
						index = ListaSolicitudesEmpleado.FindIndex(z => z.Id == id);
					}
					if (index >= 0)
					{
						int idsol = ListaSolicitudesEmpleado[index].Id;
						empleado = BuscaEmpleadoAsignacionXId(idsol);
						horariosEmpleado = horariosEmp(idsol, 0);
						obtieneConstancia(empleado.U_EMP, idsol);
					}

				}
				ViewBag.ListaSolicitudes = ListaSolicitudes(ListaSolicitudesEmpleado);
				ViewBag.HorariosEmpleado = horariosEmpleado;
			}
			catch (Exception ex)
			{
				throw ex;
			}
			return empleado;
		}

		[HttpGet]
		public ActionResult HorariosAdminStatusId(int Id)
		{
			if (Session["TypeRol"] == null && Session["NoEmp"] == null)
			{
				return RedirectToAction("Index", "Home");
			}
			EmpleadoEstudiante empleado = new EmpleadoEstudiante();
			try
			{
				empleado = AdminSolicitud(Id);

			}
			catch (Exception ex)
			{
				throw ex;
			}
			return View("SolicitudesHorarios", empleado);
		}

		public ActionResult HorariosAdminStatus()
		{
			if (Session["TypeRol"] == null && Session["NoEmp"] == null)
			{
				return RedirectToAction("Index", "Home");
			}
			EmpleadoEstudiante empleado = new EmpleadoEstudiante();
			try
			{
				empleado = AdminSolicitud();
			}
			catch (Exception ex)
			{
				throw ex;
			}
			return View("SolicitudesHorarios", empleado);
		}

		private EmpleadoEstudiante AdminSolicitud(int Id = 0)
		{
			EmpleadoEstudiante empleado = new EmpleadoEstudiante();
			try
			{
				ViewBag.Perfil = "Admin";
				List<EmpleadoEstudiante> ListaSolicitudesEmpleados = SolicitudesEstudiantesXStatus("P");
				ViewBag.ListaSolicitudes = ListaSolicitudes(ListaSolicitudesEmpleados);
				if (ListaSolicitudesEmpleados.Count() > 0)
				{
					ListaSolicitudesEmpleados = ListaSolicitudesEmpleados.OrderByDescending(x => x.Id).ToList();
					int idsol = Id;
					if (idsol == 0)
					{
						idsol = ListaSolicitudesEmpleados[0].Id;
					}
					empleado = BuscaEmpleadoAsignacionXId(idsol);
					ViewBag.HorariosEmpleado = horariosEmp(idsol, 0);
					obtieneConstancia(empleado.U_EMP, idsol);
					List<EmpleadoEstudiante> HistorialEmpleadoSeleccionado = SolicitudesHistoricoEstudiantesXEmp(empleado.U_EMP);
					ViewBag.HistorialSeleccionado = HistorialEmpleadoSeleccionado;
					ViewBag.EmpleadoSeleccionado = empleado.U_EMP;
				}
				ViewBag.Titulo = "Administrador de Horarios";
				ViewBag.Status = "P";
			}
			catch (Exception ex)
			{
				throw ex;
			}
			return empleado;
		}

		[HttpPost]
		public ActionResult FiltroAnio(int Anio, String Status)
		{
			if (Session["TypeRol"] == null && Session["NoEmp"] == null)
			{
				return RedirectToAction("Index", "Home");
			}
			EmpleadoEstudiante empleado = new EmpleadoEstudiante();
			try
			{
				ViewBag.Perfil = "Admin";
				List<EmpleadoEstudiante> ListaSolicitudesEmpleados = SolicitudesEstudiantesXStatus(Status);
				ListaSolicitudesEmpleados = ListaSolicitudesEmpleados.Where(x => x.U_FINI.Year == Anio || x.U_FFIN.Year == Anio).ToList();
				ViewBag.ListaSolicitudes = ListaSolicitudes(ListaSolicitudesEmpleados);
				List<VMHorarioLista> HorariosEmpleado = new List<VMHorarioLista>();
				if (ListaSolicitudesEmpleados.Count() > 0)
				{
					int id = ListaSolicitudesEmpleados[0].Id;
					empleado = BuscaEmpleadoAsignacionXId(id);
					HorariosEmpleado = obtenerHorariosLista(id, 0);
					ViewBag.HorariosEmpleado = horariosEmp(id, 0);
					obtieneConstancia(empleado.U_EMP, id);
				}
				ViewBag.HorariosEmpleado = HorariosEmpleado;
			}
			catch (Exception ex)
			{
				throw ex;
			}
			return View("SolicitudesHorarios", empleado);
		}

		[HttpPost]
		public ActionResult FiltroEmpleado(String Empleado, String Status)
		{
			if (Session["TypeRol"] == null && Session["NoEmp"] == null)
			{
				return RedirectToAction("Index", "Home");
			}
			EmpleadoEstudiante empleado = new EmpleadoEstudiante();
			try
			{
				ViewBag.Perfil = "Admin";
				List<EmpleadoEstudiante> ListaSolicitudesEmpleados = SolicitudesEstudiantesXStatus(Status);
				ListaSolicitudesEmpleados = ListaSolicitudesEmpleados.Where(x => x.U_EMP.Equals(Empleado)).ToList();
				ViewBag.ListaSolicitudes = ListaSolicitudes(ListaSolicitudesEmpleados);
				List<VMHorarioLista> HorariosEmpleado = new List<VMHorarioLista>();
				if (ListaSolicitudesEmpleados.Count() > 0)
				{
					int id = ListaSolicitudesEmpleados[0].Id;

PE/Views/Horarios/ConfirmacionEmpleado.cshtml
@using Aplics.Servicios.Modelos.Nominix;
@using Aplics.Servicios.Modelos.Generales;
@using Aplics.Servicios.Modelos.Horarios;
@model EmpleadoEstudiante
@{
    ViewBag.Title = "ConfirmacionEmpleado";
    List<CatalogoGeneral> catalogoUniversidades = ViewBag.CatalogoUniversidades;
    VMHorarioLista HorarioEmpleado = ViewBag.Horarios;
    Boolean MostrarEnvio = false;
    NotificacionSolicitud notificacion = new NotificacionSolicitud();
    Boolean errorNotificacion = false;
    if (ViewBag.NotificacionHorario != null)
    {
        notificacion = ViewBag.NotificacionHorario;
        errorNotificacion = notificacion.Error;
        MostrarEnvio = true;
    }
    ViewBag.Consulta=true;
}
<!-- STYLESHEETS -->
<link href="~/Content/horarios/confirmacionempleado.css" rel="stylesheet" />

<!-- CONTENT -->
@Html.Partial("~/Views/Shared/_MenuHorarios.cshtml")
<div class="confirm-view">	  
    <div class="conf-1">
        <div class="datos-conf">																	  
            <div onclick="$('#btnEditaSolicitud').click();" class="card-header" style="border-top-right-radius:15px; border-top-left-radius: 15px; background-color: #183963; color: white; height: 10vh; padding: .5rem;">
                @using (Html.BeginForm("EditaSolicitud", "Horarios", FormMethod.Post, new { @id = "formEditaSolicitud", @class = "head-card-datos" }))
                {  
                    <button type="submit" id="btnEditaSolicitud" form="formEditaSolicitud"  style=" text-transform: capitalize;background-color:#183963; border-color: #183963; height: 100%; width: 100%; border-radius: 10px; color:#FFFFFF; font-family: 'Raleway'; font-weight: 600; font-size:1.5vw; letter-spacing: 10px;">
                    <i class="icon s-6 icon-account-card-details" style="color:#FFFFFF;"></i>
                    Tus Datos
                    </button>
                    <input type="hidden" id="id" Name="id" value="@Model.Id" />
                }																														
            </div>
            <div class="crz-form-wrapper">
                @Html.Partial("~/Views/Shared/_DatosSolicitudHorario.cshtml", Model)
            </div>
        </div>
        <div class="const-conf">					
            <div class="card-header" onclick="$('#btnEditaConstancia').click();" style="border-top-right-radius:15px; border-top-left-radius: 15px; background-color: #183963; color: white; height: 10vh; padding: .5rem;">
                @using (Html.BeginForm("VisorConstanciasPDF", "Horarios", FormMethod.Post, new { @class = "head-card-datos", @id = "formEditaConstacia" }))
                {
                <button type="submit" id="btnEditaConstancia" form="formEditaConstacia" style=" text-transform: capitalize;background-color:#183963; border-color: #183963; height: 100%; width: 100%; border-radius: 10px; color:#FFFFFF; font-family: 'Raleway'; font-weight: 600; font-size:1.5vw; letter-spacing: 10px;">
                    <i class="icon s-6 icon-file-pdf" style="color:#FFFFFF;"></i>
                    Tu Constancia
                </button>
                <input type="hidden" value="@Model.U_EMP" id="claveEmpleado" name="claveEmpleado" />
                <input type="hidden" value="@Model.Id" id="Id" name="Id" />
                }
            </div>
            <div class="vis-const-conf" id="VisorPDF">
                @Html.Partial("~/Views/Shared/_Constancia.cshtml")
            </div>
        </div>
    </div>
    <div class="conf-2">
            <div class="hor-conf">
                <div class="card" style="border-radius: 15px; margin-top: 1.5em;">
                    <div onclick="$('#btnEditaHorarios').click();" class="card-header" style="border-top-right-radius:15px; border-top-left-radius: 15px; background-color: #183963; color: white; height: 10vh; padding: .5rem;">
                        @using (Html.BeginForm("Horarios", "Horarios", FormMethod.Get, new { @id = "formEditaHorarios", @class = "head-card-datos" }))
                        {											   										  
                            <button type="submit" id="btnEditaHorarios" form="formEditaHorarios" style=" text-transform: capitalize;background-color:#183963; border-color: #183963; height: 100%; width: 100%; border-radius: 10px; color:#FFFFFF; font-family: 'Raleway'; font-weight: 600; font-size:1.5vw; letter-spacing: 10px;">
                                <i class="icon s-6  icon-school" style="color:#FFFFFF;"></i>
                                Tu Horario Escolar
                            </button>
                            <input type="hidden" id="Id" Name="Id" value="@Model.Id" />
                        }
                    </div>
                </div>
                <div class="vis-hor-conf">
                    @Html.Partial("~/Views/Shared/_DetalleHorarios.cshtml", HorarioEmpleado.Horarios)
                </div>
            </div>
            <div class="instr-conf">
                <div style="width: auto; height: 36em; padding-top: 4em;">
                    <h1 class="big-text-conf"> Si nececitas</h1>
                    <h1 class="big-text-conf"> editar algo, da click</h1>
                    <h1 class="big-text-conf"> en el nombre de la </h1>
                    <h1 class="big-text-conf"> seccion en el menú superior:</h1>
                    <img style="width: 100%; margin-bottom: 2rem;" alt="" src="../assets/images/user-help/confirmar-help.png">
                    <h1 class="big-text-conf">De lo contrario,</h1>
                    <h1 class="big-text-conf">da click en Enviar.</h1>
                </div>
            </div>
    </div>
    @using (Html.BeginForm("NotificarRH", "Horarios", FormMethod.Post, new { @id = "form1", @class = "box-button-conf", onsubmit = "$('#btnEnviarHorario').prop('disabled', true);" }))
    {
        <div style="display: flex; justify-content: flex-end;">
            @if (!MostrarEnvio || errorNotificacion)
            {
                <button id="btnEnviarHorario" class="btn" style=" text-transform: capitalize;background-color:#183963; border-color: #183963; height: 6vh; width: 14vw; border-radius: 10px; color:#FFFFFF; font-family: 'Raleway'; font-weight: 900; font-size:1.5vw;" data-target="#modal-send-horario" data-toggle="modal">Enviar</button>
            }
            <input type="hidden" value="@Model.Id" id="Id" Name="Id" />
        </div>
    }

    @if (MostrarEnvio)
    {
        @Html.Partial("~/Views/Shared/_NotificacionEnvioSolicitud.cshtml", notificacion)
        <script language="javascript" type="text/javascript">
            $(document).ready(function () {
                $("#modal-send-solicitud").modal("show");
            });
        </script>
    }
</div>

PE/Views/Horarios/ControHorarios.cshtml
@model Aplics.Servicios.Modelos.Horarios.EmpleadoEstudiante
@{
    ViewBag.Title = "ControHorarios";
}

<!-- STYLESHEETS -->
<link href="~/Content/horarios/controhorarios.css?V=1.7" rel="stylesheet" />
<!-- CONTENT -->
@*@Html.Partial("~/Views/Shared/_MenuHorarios.cshtml")*@

<div class="hor-container">
    <div class="instructions">
        <i class="icon s-15  icon-account-card-details" style="color:#00464E"></i>
        <h2>
            Información Básica
        </h2>
        <h2>
            Rellena tus datos personales
        </h2>
        <div style="margin-top:2rem; margin-bottom: 2rem;">
            <img class="img-fluid" src="~/assets/images/user-help/user.png" />
        </div>
        <div class="instructions-p">
            <p style="margin-top: 2rem; margin-bottom: 2rem;">
                Recuerda cargar correctamente la vigencia, para evitar que se
                empalmen las fechas en caso de realizar veranos o cursos adicionales.
            </p>

            <p style="margin-top: 2rem; margin-bottom: 2rem;">
                Deberás indicar la fecha exacta de inicio y fecha exacta del fin de
                tu periodo escolar.
            </p>
        </div>
        <i class="icon s-17  icon-file-move" style="color:#00464E;"></i>
    </div>
    <div class="est-data">
        @Html.Partial("~/Views/Shared/_DatosSolicitudHorario.cshtml", Model)
    </div>
</div>
<!-- CONTENT -->