PE/Controllers/LoginController.cs
using Aplics.Servicios.Entidades.Horarios;
using Aplics.Servicios.Modelos.Nominix;
using GRC.Servicios.ClienteRestNF;
using PortalEmpleadosV2.DataQuerys;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;
using System.Linq;
using System.Security.Principal;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PortalEmpleadosV2.Controllers
{
    public class LoginController : Controller
    {
        private String urlAPINominix = ConfigurationManager.AppSettings["BaseURLServiciosNominix"];
        private String urlAPIAgilix = ConfigurationManager.AppSettings["BaseURLServiciosAgilix"];
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(string a, FormCollection fc)
        {
            var isValidUser = false;

            try
            {
                //OBTENEMOS LA DATA
                LoginAcceso dataGeneral = new LoginAcceso();
                if (Debugger.IsAttached)
                {     
                    DataInsert di = new DataInsert();
                    dataGeneral = di.sp_ObtenDataLogin(fc["user"], fc["password"]).FirstOrDefault<LoginAcceso>();
                }else
                {
                    //aqui se construye el token

                    //aqui se llama el API, para traer los datos de acceso GET
                    //Crear un cliente del tipo del objeto devuelto:
                    ClienteRest<LoginAcceso> cliente = new ClienteRest<LoginAcceso>();
                    //Hacer GET al Api Agilix:
                    dataGeneral = await cliente.LLamarServicioPutGeneral<String>(urlAPIAgilix, "AccesoAgilix/" + fc["user"], fc["password"]);
                }

                if (dataGeneral != null)
                {
                    isValidUser = true;
                    Session["NoEmp"] = fc["user"];
                    Session["Notificaciones"] = "15";
                    Session["NombreEmpleado"] = dataGeneral.NombreEmpleado == null ? "No se tiene nombre del empleado" : dataGeneral.NombreEmpleado;
                    Session["AnioIngreso"] = dataGeneral.AnioIngreso;
                    //una vez que agregue el campo reemplazar en todos los lugares donde se le pasa el user sign por esta variable de sesión.
                    Session["UserSign"] = dataGeneral.UserSign;

                    //se agrega para cuando se utiliza el calendario activar ciertas funciones
                    Session["CalendarioActivo"] = false;

                    //variable de sesion para indicar el tipo de rol
                    //1 = Admin,2 = Manager, 3 = Empleado
                    Session["TypeRol"] = dataGeneral.TipoRol;
                    if(dataGeneral.TipoRol == null)
                    {
                        Session["NoEmp"] = null;
                        ViewData["invalidPass"] = "El tipo de usuario no está configurado, por favor verificarlo con sistemas.";
                    } else
                    {
                        Session["TypeRolMenuSup"] = dataGeneral.TipoRol;
                        Session["idSolicitud"] = null;
                    }
                }
                else
                {
                    ViewData["invalidPass"] = "Contraseña inválida";
                }

                //Session["NoEmp"] = fc["user"];
                //Session["Notificaciones"] = "15";

                //Session["NombreEmpleado"] = "Juan Pérez";
                //Session["AnioIngreso"] = "2017";

                ////variable de sesion para indicar el tipo de rol
                ////1 = Admin,2 = Ma    nager, 3 = Estudiante, 4 = Empleado
                //Session["TypeRol"] = 1;
                //Session["TypeRolMenuSup"] = 1;
            } catch (Exception ex)
            {
                throw ex;
            }

            if (isValidUser)
            {
                if (Convert.ToInt32(Session["TypeRol"]) == 1 || Convert.ToInt32(Session["TypeRol"]) == 2)
                {
                    return RedirectToAction("AdminSolicitudesPermisos", "Permisos");
                }
                else
                {
                    return RedirectToAction("ListaPermisos", "Permisos");
                }

            } else {
                return View();
            }
            //return RedirectToAction("test", "Home");
        }

        
    }
}

PE/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>APLICS - LOGIN</title>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/favicon.ico" />

    @Scripts.Render("~/bundles/modernizr")

    <!-- FUSE THEME -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700italic,700,900,900italic" rel="stylesheet">

    <!-- STYLESHEETS FUSE THEME -->
    <style type="text/css">
        [fuse-cloak],
        .fuse-cloak {
            display: none !important;
        }
    </style>
    <!-- STYLESHEETS -->
    <link href="~/Content/shared/index-login.css?V=3.5" rel="stylesheet" />


    <link type="text/css" rel="stylesheet" href="~/assets/icons/fuse-icon-font/style.css">
    <!-- Animate.css FUSE THEM -->
    <link type="text/css" rel="stylesheet" href="~/assets/modulos/animate.css/animate.min.css">
    <!-- PNotify FUSE THEME -->
    <link type="text/css" rel="stylesheet" href="~/assets/modulos/pnotify/dist/PNotifyBrightTheme.css">
    <!-- Nvd3 - D3 Charts -->
    <link type="text/css" rel="stylesheet" href="~/assets/modulos/nvd3/build/nv.d3.min.css" />
    <!-- Perfect Scrollbar -->
    <link type="text/css" rel="stylesheet" href="~/assets/modulos/perfect-scrollbar/css/perfect-scrollbar.css" />
    <!-- Fuse Html -->
    <link type="text/css" rel="stylesheet" href="~/assets/fuse-html/fuse-html.min.css" />
    <!-- Main CSS -->
    <link type="text/css" rel="stylesheet" href="~/assets/css/main.css">
    <!-- / STYLESHEETS -->
    <!-- JAVASCRIPT -->
    <!-- jQuery -->
    <script type="text/javascript" src="~/assets/modulos/jquery/dist/jquery.min.js"></script>
    <!-- Mobile Detect -->
    <script type="text/javascript" src="~/assets/modulos/mobile-detect/mobile-detect.min.js"></script>
    <!-- Perfect Scrollbar -->
    <script type="text/javascript" src="~/assets/modulos/perfect-scrollbar/dist/perfect-scrollbar.min.js"></script>
    <!-- Popper.js -->
    <script type="text/javascript" src="~/assets/modulos/popper.js/dist/umd/popper.min.js"></script>
    <!-- Bootstrap -->
    <script type="text/javascript" src="~/assets/modulos/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Nvd3 - D3 Charts -->
    <script type="text/javascript" src="~/assets/modulos/d3/d3.min.js"></script>
    <script type="text/javascript" src="~/assets/modulos/nvd3/build/nv.d3.min.js"></script>
    <!-- Data tables -->
    <script type="text/javascript" src="~/assets/modulos/datatables.net/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="~/assets/modulos/datatables-responsive/js/dataTables.responsive.js"></script>
    <!-- PNotify -->
    <script type="text/javascript" src="~/assets/modulos/pnotify/dist/iife/PNotify.js"></script>
    <script type="text/javascript" src="~/assets/modulos/pnotify/dist/iife/PNotifyStyleMaterial.js"></script>
    <script type="text/javascript" src="~/assets/modulos/pnotify/dist/iife/PNotifyButtons.js"></script>
    <script type="text/javascript" src="~/assets/modulos/pnotify/dist/iife/PNotifyCallbacks.js"></script>
    <script type="text/javascript" src="~/assets/modulos/pnotify/dist/iife/PNotifyMobile.js"></script>
    <script type="text/javascript" src="~/assets/modulos/pnotify/dist/iife/PNotifyHistory.js"></script>
    <script type="text/javascript" src="~/assets/modulos/pnotify/dist/iife/PNotifyDesktop.js"></script>
    <script type="text/javascript" src="~/assets/modulos/pnotify/dist/iife/PNotifyConfirm.js"></script>
    <script type="text/javascript" src="~/assets/modulos/pnotify/dist/iife/PNotifyReference.js"></script>
    <!-- Fuse Html -->
    <script type="text/javascript" src="~/assets/fuse-html/fuse-html.min.js"></script>
    <!-- Main JS -->
    <script type="text/javascript" src="~/assets/js/main.js"></script>
    <!-- / JAVASCRIPT -->

</head>
<body class="layout layout-vertical layout-left-navigation layout-above-toolbar layout-above-footer">
    <main>
        @if (ViewBag.WinAut != null)
        {
            <span>Autenticación de Windows</span>
        }
        <div id="wrapper">
            <div class="content-wrapper">
                <div class="content custom-scrollbar" style="overflow-y:scroll !important;">
                    <div class="row no-gutters bkg-log">
                        <div class="intro col-12 col-md light-fg">
                            <div class="d-flex flex-column align-items-center align-items-md-start text-center text-md-left py-16 py-md-32 px-12">
                                <div class="title">
                                    <img class="crz-img" src="~/images/logo-aaacesa.svg" />
                                </div>
                                <div class="description pt-2" style="font-family:'Raleway'; font-size: 3rem; margin-left: 1%; color: #183963;">
                                    <p>Bienvenid@@</p>
                                    <p>Ingresa tu usuario y contraseña para comenzar.</p>
                                </div>
                            </div>
                        </div>
                        <div class="form-wrapper col-12 col-md-auto d-flex justify-content-center p-4 p-md-0">
                            <div class="form-content md-elevation-8 h-100 bg-white text-auto py-16 py-md-32 px-12">
                                <div class="title h5" style="color: #183963">Inicia con tu Cuenta</div>
                                @using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @id = "form1", @class = "mt-8" }))
                                {
                                    <div class="form-group mb-4">
                                        <input type="text" class="form-control" id="user" name="user" placeholder=" " />
                                        @*@Html.TextBox("user", ViewBag.user as string, new { id = "user", @class = "form-control" })*@
                                        <label for="user">Usuario</label>

                                        @*@Html.LabelFor(x => x.user)*@
                                        @*@Html.TextBoxFor(x => x.user, new { @id = "user", @class = "form-control", @name = "user" })
                                            <label for="user">Usuario</label>
                                            @Html.ValidationMessageFor(x => x.user, null, new { @class = "text-danger" })*@

                                    </div>
                                    <div class="form-group mb-4">
                                        <input type="password" class="form-control" id="password" name="password" placeholder=" " />
                                        @*@Html.TextBox("password", ViewBag.password as string, new { id = "password", @class = "form-control", placeholder = " ", type = "password" })*@
                                        <label for="password">Contraseña</label>
                                        <p class="invalid-password">@ViewData["invalidPass"]</p>

                                        @*@Html.TextBoxFor(x => x.password, new { @id = "password", @class = "form-control", @name = "password" })
                                            <label for="password">Contraseña</label>
                                            @Html.ValidationMessageFor(x => x.password, null, new { @class = "text-danger" })*@


                                    </div>
                                    @*if (ViewBag.ErrorLogin)
                                        {
                                            <p style="color:red; font-size:10px;"><i class="icon-bell"></i>El usuario y password no son validos</p>
                                        }*@

                                    <div class="remember-forgot-password row no-gutters align-items-center justify-content-between pt-4">

                                        <a href="#" class="forgot-password text-secondary mb-4">¿Olvidaste tu Contraseña?</a>
                                    </div>
                                    @*<asp:Button ID="btnEntrar" runat="server" Width="100%" Text="ENTRAR" class="submit-button btn btn-block btn-secondary my-4 mx-auto">ENTRAR</asp:Button>*@
                                    <button type="submit" class="submit-button btn btn-block btn-secondary my-4 mx-auto" style="background-color: #183963;">ENTRAR</button>
                                }
                                @*<form name="loginForm" id="form1" novalidate class="mt-8" method="post">*@

                                @*</form>*@
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </main>
    <script type="text/javascript" src="~/Scripts/jquery.validate.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</body>
</html>